
// Kivi Sakset Paperi //
 
import java.util.Random; 
import javax.swing.JOptionPane;
public class JApplet_Kivi extends javax.swing.JApplet {

private static String Lasku() {

    String Tietokone = "";
    int Random; 
    
    Random generator = new Random(); 

    Random = generator.nextInt(3)+1; 

    if (Random == 1) 
       Tietokone = "K"; 
    else if (Random == 2) 
       Tietokone = "P"; 
    else if (Random == 3) 
       Tietokone = "S"; 
    return Tietokone ;
}
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JApplet_Kivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JApplet_Kivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JApplet_Kivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JApplet_Kivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(jTree1);

        jTextField1.setText("K, P tai S");

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

    String Tuomo = jTextField1.getText();
        Tuomo = Tuomo.toUpperCase(); 
 String Tietokone=Lasku();
            
            jTextPane1.setText("Tietokone valitsi: " + Tietokone); 



   if (Tuomo.equalsIgnoreCase(Tietokone)) {
   jTextPane1.setText(jTextPane1.getText() +"\tTasapeli!");
}
else if (Tuomo.equalsIgnoreCase("K")) {
   if (Lasku().equalsIgnoreCase("S")) 
      jTextPane1.setText(jTextPane1.getText() +"\tKivi voittaa sakset. Voitit!!");
   else if (Tietokone.equalsIgnoreCase("P")) 
        jTextPane1.setText(jTextPane1.getText() +"\tPaperi voittaa kiven. Hävisit!!");
}
else if (Tuomo.equalsIgnoreCase("P")) {
   if (Tietokone.equalsIgnoreCase("S")) 
       jTextPane1.setText(jTextPane1.getText() +"\tSakset voittavat paperin. Hävisit!!"); 
   else if (Tietokone.equalsIgnoreCase("K")) 
        jTextPane1.setText(jTextPane1.getText() +"\tPapeeri voittaaa kiven. Voitit!!");
} 
else if (Tuomo.equalsIgnoreCase("S")) {
     if (Tietokone.equalsIgnoreCase("P")) 
         jTextPane1.setText(jTextPane1.getText() +"\tSakset voittavat paperin. Voitit!!"); 
     else if (Tietokone.equalsIgnoreCase("K")) 
        jTextPane1.setText(jTextPane1.getText() +"\tKivi voittaa sakset. Hävisit!!");
}
else 
     jTextPane1.setText(jTextPane1.getText() +"Error.");
    }//GEN-LAST:event_jButton1MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}